name: Daily Telegram Message (Alternative)

on:
  schedule:
    - cron: "30 4 * * *" # 10:00 AM IST
  workflow_dispatch:

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
          CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
          
          MESSAGE="🌅 Good morning! $(date '+%A, %B %d, %Y') - Your daily reminder via Telegram! 💪"
          
          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=$MESSAGE" \
            -d "parse_mode=HTML"