name: WhatsApp via Maytapi (Free 1000 messages/month)

on:
  schedule:
    - cron: "30 4 * * *" # 10:00 AM IST
  workflow_dispatch:

jobs:
  send-whatsapp-maytapi:
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp via Maytapi
        run: |
          PRODUCT_ID="${{ secrets.MAYTAPI_PRODUCT_ID }}"
          PHONE_ID="${{ secrets.MAYTAPI_PHONE_ID }}"
          API_TOKEN="${{ secrets.MAYTAPI_API_TOKEN }}"
          
          TO_NUMBER="917528940605"
          MESSAGE="🌅 Good morning! $(date '+%A, %B %d, %Y') - Your daily Maytapi reminder! 💪"
          
          echo "📱 Sending WhatsApp via Maytapi to +$TO_NUMBER"
          
          curl -X POST "https://api.maytapi.com/api/$PRODUCT_ID/$PHONE_ID/sendMessage" \
            -H "Content-Type: application/json" \
            -H "x-maytapi-key: $API_TOKEN" \
            -d "{
              \"to_number\": \"$TO_NUMBER\",
              \"type\": \"text\",
              \"message\": \"$MESSAGE\"
            }"

  fallback-notification:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Email Notification on Failure
        run: |
          echo "WhatsApp sending failed, check your API credentials"